### ISSUE TITLE
Unable to change language

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#242]
Doesnt work in any browser.

**Comment by narsuman** [comment]
Fixed ?

**Comment by Temetz** [comment]
@AatuPitkanen & @nikolauska You both seem to have made fixes in your local branches releated to this issue. Please discuss whose changes will be put forward to pull request.

@narsuman Not fixed yet. Waiting for a pull request to be done.
